// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAdsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "ads",
		Short:       "Search Subito listings (annunci) through the site's own search backend",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAdsCheckCmd(flags))
	cmd.AddCommand(newAdsRecommendedCmd(flags))
	cmd.AddCommand(newAdsSearchCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelAdsHistoryCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelAdsRiskCmd(flags))
	return cmd
}
