// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAdsCheckCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagC string
	var flagR string
	var flagT string
	var flagSort string
	var flagLast string

	cmd := &cobra.Command{
		Use:         "check",
		Short:       "Ask whether a search has new listings since a given listing urn (cheap, no listing data)",
		Example:     "  subito-pp-cli ads check --query iphone --last id:ad:550e8400-e29b-41d4-a716-446655440000:list:663298311",
		Annotations: map[string]string{"pp:endpoint": "ads.check", "pp:method": "GET", "pp:path": "/search/items/check", "mcp:read-only": "true", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("last") && flagLast == "" && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "last")
			}
			path := "/search/items/check"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagQ != "" {
				params["q"] = formatCLIParamValue(flagQ)
			}
			if flagC != "" {
				params["c"] = formatCLIParamValue(flagC)
			}
			if flagR != "" {
				params["r"] = formatCLIParamValue(flagR)
			}
			if flagT != "" {
				params["t"] = formatCLIParamValue(flagT)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			if flagLast != "" {
				params["last"] = formatCLIParamValue(flagLast)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "ads", false, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"count": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"count": true})
		},
	}
	cmd.Flags().StringVar(&flagQ, "query", "", "Keywords, same as ads search")
	cmd.Flags().StringVar(&flagQ, "q", "", "Keywords, same as ads search")
	_ = cmd.Flags().MarkHidden("q")
	cmd.Flags().StringVar(&flagC, "category-id", "", "Category id")
	cmd.Flags().StringVar(&flagR, "region-id", "", "Region id")
	cmd.Flags().StringVar(&flagT, "ad-type", "s", "Ad type key")
	cmd.Flags().StringVar(&flagSort, "sort", "datedesc", "Sort order (keep datedesc)")
	cmd.Flags().StringVar(&flagLast, "last", "", "Urn of the newest listing already seen")

	return cmd
}
