// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAdsSearchCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagC string
	var flagT string
	var flagR string
	var flagCi string
	var flagTo string
	var flagPs int
	var flagPe int
	var flagShp bool
	var flagQso bool
	var flagAdvt string
	var flagSort string
	var flagLim int
	var flagStart int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "search",
		Short:       "Search listings by keyword, category, place, price and more. Returns newest first by default.",
		Example:     "  subito-pp-cli ads search --query \"bici da corsa\" --category-id 41 --region-id 4 --price-min 200 --price-max 1500",
		Annotations: map[string]string{"pp:endpoint": "ads.search", "pp:method": "GET", "pp:path": "/search/items", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("ad-type") {
				allowedT := []string{"s", "k", "u", "h", "g"}
				validT := false
				for _, v := range allowedT {
					if flagT == v {
						validT = true
						break
					}
				}
				if !validT {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagT, "ad-type", allowedT)
				}
			}
			if cmd.Flags().Changed("advertiser-type") {
				allowedAdvt := []string{"0,2", "1"}
				validAdvt := false
				for _, v := range allowedAdvt {
					if flagAdvt == v {
						validAdvt = true
						break
					}
				}
				if !validAdvt {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagAdvt, "advertiser-type", allowedAdvt)
				}
			}
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"datedesc", "relevance", "priceasc", "pricedesc"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSort, "sort", allowedSort)
				}
			}
			path := "/search/items"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "ads", path, retainCLIQueryParams(cmd, map[string]string{
				"q":     formatCLIParamValue(flagQ),
				"c":     formatCLIParamValue(flagC),
				"t":     formatCLIParamValue(flagT),
				"r":     formatCLIParamValue(flagR),
				"ci":    formatCLIParamValue(flagCi),
				"to":    formatCLIParamValue(flagTo),
				"ps":    formatCLIParamValue(flagPs),
				"pe":    formatCLIParamValue(flagPe),
				"shp":   formatCLIParamValue(flagShp),
				"qso":   formatCLIParamValue(flagQso),
				"advt":  formatCLIParamValue(flagAdvt),
				"sort":  formatCLIParamValue(flagSort),
				"lim":   formatCLIParamValue(flagLim),
				"start": formatCLIParamValue(flagStart),
			}, map[string][]string{"q": {"query", "q"}, "c": {"category-id"}, "t": {"ad-type"}, "r": {"region-id"}, "ci": {"province-id"}, "to": {"town-istat"}, "ps": {"price-min"}, "pe": {"price-max"}, "shp": {"shippable"}, "qso": {"title-only"}, "advt": {"advertiser-type"}, "sort": {"sort"}, "lim": {"page-size"}, "start": {"start"}}, "start", "offset"), nil, flagAll, "start", "offset", "lim", 30, "", "", "ads", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
					selectErr = selectErrorForDryRun(selectErr, flags, data)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"type": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"type": true})
		},
	}
	cmd.Flags().StringVar(&flagQ, "query", "", "Keywords (Subito matches loosely and mixes nearby models)")
	cmd.Flags().StringVar(&flagQ, "q", "", "Keywords (Subito matches loosely and mixes nearby models)")
	_ = cmd.Flags().MarkHidden("q")
	cmd.Flags().StringVar(&flagC, "category-id", "", "Category id (see 'categories list'), e.g. 2 Auto, 41 Biciclette, 12 Telefonia, 10 Informatica")
	cmd.Flags().StringVar(&flagT, "ad-type", "s", "Ad type key: s vendita, k cerco, u affitto, h affitto vacanze, g regalo (one of: s, k, u, h, g)")
	cmd.Flags().StringVar(&flagR, "region-id", "", "Region id (see 'geo regions'), e.g. 4 Lombardia")
	cmd.Flags().StringVar(&flagCi, "province-id", "", "Province id within the region (see 'geo provinces')")
	cmd.Flags().StringVar(&flagTo, "town-istat", "", "Town ISTAT code (see 'geo towns'), e.g. 015146 Milano")
	cmd.Flags().IntVar(&flagPs, "price-min", 0, "Minimum price in euro")
	cmd.Flags().IntVar(&flagPe, "price-max", 0, "Maximum price in euro")
	cmd.Flags().BoolVar(&flagShp, "shippable", false, "Only listings that can be shipped (TuttoSubito)")
	cmd.Flags().BoolVar(&flagQso, "title-only", false, "Match keywords in the title only")
	cmd.Flags().StringVar(&flagAdvt, "advertiser-type", "", "Advertiser type: '0,2' private, '1' verified dealer (shop) (one of: 0,2, 1)")
	cmd.Flags().StringVar(&flagSort, "sort", "datedesc", "Sort order (one of: datedesc, relevance, priceasc, pricedesc)")
	cmd.Flags().IntVar(&flagLim, "page-size", 30, "Listings per page (max 100)")
	cmd.Flags().IntVar(&flagStart, "start", 0, "Offset of the first listing")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
