// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNotificationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "notifications",
		Short:       "Configure global notification endpoints that can be used across all your watches.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNotificationsAddCmd(flags))
	cmd.AddCommand(newNotificationsDeleteCmd(flags))
	cmd.AddCommand(newNotificationsGetCmd(flags))
	cmd.AddCommand(newNotificationsReplaceCmd(flags))
	return cmd
}
