// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newBulkImportPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagTagUuids string
	var flagTag string
	var flagProxy string
	var flagDedupe bool

	cmd := &cobra.Command{
		Use:         "bulk-import",
		Short:       "Import a list of URLs to monitor with optional watch configuration. Accepts line-separated URLs in request body.",
		Long:        "Import a list of URLs to monitor with optional watch configuration. Accepts line-separated URLs in request body.",
		Example:     "  changedetection-pp-cli bulk-import",
		Annotations: map[string]string{"pp:endpoint": "bulk_import.import-watches", "pp:method": "POST", "pp:path": "/import"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/import"
			params := map[string]string{}
			if flagTagUuids != "" {
				params["tag_uuids"] = formatCLIParamValue(flagTagUuids)
			}
			if flagTag != "" {
				params["tag"] = formatCLIParamValue(flagTag)
			}
			if flagProxy != "" {
				params["proxy"] = formatCLIParamValue(flagProxy)
			}
			if flagDedupe != false {
				params["dedupe"] = formatCLIParamValue(flagDedupe)
			}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "bulk_import", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagTagUuids, "tag-uuids", "", "Tag UUID(s) to apply to imported watches (comma-separated for multiple)")
	cmd.Flags().StringVar(&flagTag, "tag", "", "Tag name to apply to imported watches")
	cmd.Flags().StringVar(&flagProxy, "proxy", "", "Proxy key to use for imported watches")
	cmd.Flags().BoolVar(&flagDedupe, "dedupe", true, "Skip duplicate URLs (default true)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
