// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTagCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "tag",
		Short:       "Get, create, update, and delete tag",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTagCreateCmd(flags))
	cmd.AddCommand(newTagDeleteCmd(flags))
	cmd.AddCommand(newTagGetCmd(flags))
	cmd.AddCommand(newTagUpdateCmd(flags))
	return cmd
}
