// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWatchDifferenceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "difference",
		Short:       "Get difference for watch",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWatchDifferenceGetWatchHistoryDiffCmd(flags))
	return cmd
}
