// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newWatchDifferenceGetWatchHistoryDiffCmd(flags *rootFlags) *cobra.Command {
	var flagFormat string
	var flagWordDiff string
	var flagNoMarkup string
	var flagType string
	var flagChangesOnly string
	var flagIgnoreWhitespace string
	var flagRemoved string
	var flagAdded string
	var flagReplaced string

	cmd := &cobra.Command{
		Use:         "get-watch-history-diff <uuid> <from_timestamp> <to_timestamp>",
		Aliases:     []string{"get"},
		Short:       "Generate a difference (comparison) between two historical snapshots of a web page change monitor (watch).",
		Example:     "  changedetection-pp-cli watch difference get-watch-history-diff 550e8400-e29b-41d4-a716-446655440000 previous latest",
		Annotations: map[string]string{"pp:endpoint": "difference.get-watch-history-diff", "pp:method": "GET", "pp:path": "/watch/{uuid}/difference/{from_timestamp}/{to_timestamp}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("format") {
				allowedFormat := []string{"text", "html", "htmlcolor", "markdown"}
				validFormat := false
				for _, v := range allowedFormat {
					if flagFormat == v {
						validFormat = true
						break
					}
				}
				if !validFormat {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagFormat, "format", allowedFormat)
				}
			}
			if cmd.Flags().Changed("word-diff") {
				allowedWordDiff := []string{"true", "false", "1", "0", "yes", "no", "on", "off"}
				validWordDiff := false
				for _, v := range allowedWordDiff {
					if flagWordDiff == v {
						validWordDiff = true
						break
					}
				}
				if !validWordDiff {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagWordDiff, "word-diff", allowedWordDiff)
				}
			}
			if cmd.Flags().Changed("no-markup") {
				allowedNoMarkup := []string{"true", "false", "1", "0", "yes", "no", "on", "off"}
				validNoMarkup := false
				for _, v := range allowedNoMarkup {
					if flagNoMarkup == v {
						validNoMarkup = true
						break
					}
				}
				if !validNoMarkup {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagNoMarkup, "no-markup", allowedNoMarkup)
				}
			}
			if cmd.Flags().Changed("type") {
				allowedType := []string{"diffLines", "diffWords"}
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagType, "type", allowedType)
				}
			}
			if cmd.Flags().Changed("changes-only") {
				allowedChangesOnly := []string{"true", "false", "1", "0", "yes", "no", "on", "off"}
				validChangesOnly := false
				for _, v := range allowedChangesOnly {
					if flagChangesOnly == v {
						validChangesOnly = true
						break
					}
				}
				if !validChangesOnly {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagChangesOnly, "changes-only", allowedChangesOnly)
				}
			}
			if cmd.Flags().Changed("ignore-whitespace") {
				allowedIgnoreWhitespace := []string{"true", "false", "1", "0", "yes", "no", "on", "off"}
				validIgnoreWhitespace := false
				for _, v := range allowedIgnoreWhitespace {
					if flagIgnoreWhitespace == v {
						validIgnoreWhitespace = true
						break
					}
				}
				if !validIgnoreWhitespace {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagIgnoreWhitespace, "ignore-whitespace", allowedIgnoreWhitespace)
				}
			}
			if cmd.Flags().Changed("removed") {
				allowedRemoved := []string{"true", "false", "1", "0", "yes", "no", "on", "off"}
				validRemoved := false
				for _, v := range allowedRemoved {
					if flagRemoved == v {
						validRemoved = true
						break
					}
				}
				if !validRemoved {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagRemoved, "removed", allowedRemoved)
				}
			}
			if cmd.Flags().Changed("added") {
				allowedAdded := []string{"true", "false", "1", "0", "yes", "no", "on", "off"}
				validAdded := false
				for _, v := range allowedAdded {
					if flagAdded == v {
						validAdded = true
						break
					}
				}
				if !validAdded {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagAdded, "added", allowedAdded)
				}
			}
			if cmd.Flags().Changed("replaced") {
				allowedReplaced := []string{"true", "false", "1", "0", "yes", "no", "on", "off"}
				validReplaced := false
				for _, v := range allowedReplaced {
					if flagReplaced == v {
						validReplaced = true
						break
					}
				}
				if !validReplaced {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagReplaced, "replaced", allowedReplaced)
				}
			}
			path := "/watch/{uuid}/difference/{from_timestamp}/{to_timestamp}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("uuid is required\nUsage: %s <%s>", cmd.CommandPath(), "uuid"))
			}
			path = replacePathParam(path, "uuid", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("from_timestamp is required\nUsage: %s <%s>", cmd.CommandPath(), "from_timestamp"))
			}
			path = replacePathParam(path, "from_timestamp", args[1])
			if len(args) < 3 || args[2] == "" {
				return usageErr(fmt.Errorf("to_timestamp is required\nUsage: %s <%s>", cmd.CommandPath(), "to_timestamp"))
			}
			path = replacePathParam(path, "to_timestamp", args[2])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagFormat != "" {
				params["format"] = formatCLIParamValue(flagFormat)
			}
			if flagWordDiff != "" {
				params["word_diff"] = formatCLIParamValue(flagWordDiff)
			}
			if flagNoMarkup != "" {
				params["no_markup"] = formatCLIParamValue(flagNoMarkup)
			}
			if flagType != "" {
				params["type"] = formatCLIParamValue(flagType)
			}
			if flagChangesOnly != "" {
				params["changesOnly"] = formatCLIParamValue(flagChangesOnly)
			}
			if flagIgnoreWhitespace != "" {
				params["ignoreWhitespace"] = formatCLIParamValue(flagIgnoreWhitespace)
			}
			if flagRemoved != "" {
				params["removed"] = formatCLIParamValue(flagRemoved)
			}
			if flagAdded != "" {
				params["added"] = formatCLIParamValue(flagAdded)
			}
			if flagReplaced != "" {
				params["replaced"] = formatCLIParamValue(flagReplaced)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "difference", false, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagFormat, "format", "text", "Output format for the diff: - `text` (default): Plain text with (removed) and (added) prefixes - `html` (one of: text, html, htmlcolor, markdown)")
	cmd.Flags().StringVar(&flagWordDiff, "word-diff", "false", "Enable word-level diffing for more granular comparisons. (one of: true, false, 1, 0, yes, no, on, off)")
	cmd.Flags().StringVar(&flagNoMarkup, "no-markup", "false", "When set to true, returns the raw diff content without any markup formatting. (one of: true, false, 1, 0, yes, no, on, off)")
	cmd.Flags().StringVar(&flagType, "type", "diffLines", "Diff granularity type: - `diffLines` (default): Line-level comparison, showing which lines changed - `diffWords` (one of: diffLines, diffWords)")
	cmd.Flags().StringVar(&flagChangesOnly, "changes-only", "true", "When enabled, only show lines/content that changed (no surrounding context). (one of: true, false, 1, 0, yes, no, on, off)")
	cmd.Flags().StringVar(&flagIgnoreWhitespace, "ignore-whitespace", "false", "When enabled, ignore whitespace-only changes (spaces, tabs, newlines). (one of: true, false, 1, 0, yes, no, on, off)")
	cmd.Flags().StringVar(&flagRemoved, "removed", "true", "Include removed/deleted content in the diff output. When disabled, content that was deleted will not appear in the diff. (one of: true, false, 1, 0, yes, no, on, off)")
	cmd.Flags().StringVar(&flagAdded, "added", "true", "Include added/new content in the diff output. When disabled, content that was added will not appear in the diff. (one of: true, false, 1, 0, yes, no, on, off)")
	cmd.Flags().StringVar(&flagReplaced, "replaced", "true", "Include replaced/modified content in the diff output. (one of: true, false, 1, 0, yes, no, on, off)")

	return cmd
}
