// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"changedetection-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newWatchCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyBody string
	var bodyBrowserSteps string
	var bodyCheckUniqueLines bool
	var bodyConditions string
	var bodyConditionsMatchLogic string
	var bodyDateCreated int
	var bodyExtractLinesContaining string
	var bodyExtractText string
	var bodyFetchBackend string
	var bodyFilterFailureNotificationSend bool
	var bodyFilterTextAdded bool
	var bodyFilterTextRemoved bool
	var bodyFilterTextReplaced bool
	var bodyFollowPriceChanges bool
	var bodyHasLdjsonPriceData bool
	var bodyHeaders string
	var bodyHistorySnapshotMaxLength int
	var bodyIgnoreStatusCodes bool
	var bodyIgnoreText string
	var bodyInStockOnly bool
	var bodyIncludeFilters string
	var bodyLlmChangeSummary string
	var bodyLlmEvaluationCache string
	var bodyLlmIntent string
	var bodyLlmLastTokensUsed int
	var bodyLlmPrefilter string
	var bodyLlmTokensPeriodKey string
	var bodyLlmTokensThisPeriod int
	var bodyLlmTokensUsedCumulative int
	var bodyMethod string
	var bodyNotificationBody string
	var bodyNotificationFormat string
	var bodyNotificationMuted bool
	var bodyNotificationScreenshot bool
	var bodyNotificationTitle string
	var bodyNotificationUrls string
	var bodyPaused bool
	var bodyPriceChangeThresholdPercent float64
	var bodyProcessor string
	var bodyProxy string
	var bodyRemoveDuplicateLines bool
	var bodySortTextAlphabetically bool
	var bodyStripIgnoredLines bool
	var bodySubtractiveSelectors string
	var bodyTag string
	var bodyTags string
	var bodyTextShouldNotBePresent string
	var bodyTimeBetweenCheckDays int
	var bodyTimeBetweenCheckHours int
	var bodyTimeBetweenCheckMinutes int
	var bodyTimeBetweenCheckSeconds int
	var bodyTimeBetweenCheckWeeks int
	var bodyTimeBetweenCheckUseDefault bool
	var bodyTimeScheduleLimitEnabled bool
	var bodyTimeScheduleLimitFridayEnabled bool
	var bodyTimeScheduleLimitFridayStartTime string
	var bodyTimeScheduleLimitMondayEnabled bool
	var bodyTimeScheduleLimitMondayStartTime string
	var bodyTimeScheduleLimitSaturdayEnabled bool
	var bodyTimeScheduleLimitSaturdayStartTime string
	var bodyTimeScheduleLimitSundayEnabled bool
	var bodyTimeScheduleLimitSundayStartTime string
	var bodyTimeScheduleLimitThursdayEnabled bool
	var bodyTimeScheduleLimitThursdayStartTime string
	var bodyTimeScheduleLimitTuesdayEnabled bool
	var bodyTimeScheduleLimitTuesdayStartTime string
	var bodyTimeScheduleLimitWednesdayEnabled bool
	var bodyTimeScheduleLimitWednesdayStartTime string
	var bodyTitle string
	var bodyTrackLdjsonPriceData bool
	var bodyTriggerText string
	var bodyTrimTextWhitespace bool
	var bodyUrl string
	var bodyUsePageTitleInList bool
	var bodyUuid string
	var bodyWebdriverDelay int
	var bodyWebdriverJsExecuteCode string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create a single web page change monitor (watch). Requires at least `url` to be set.",
		Example:     "  changedetection-pp-cli watch create --url https://example.com/resource",
		Annotations: map[string]string{"pp:endpoint": "watch.create", "pp:method": "POST", "pp:path": "/watch"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("url") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "url")
				}
			}
			path := "/watch"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyBody != "" {
					body["body"] = bodyBody
				}
				if bodyBrowserSteps != "" {
					var parsedBrowserSteps any
					if err := json.Unmarshal([]byte(bodyBrowserSteps), &parsedBrowserSteps); err != nil {
						return fmt.Errorf("parsing --browser-steps JSON: %w", err)
					}
					body["browser_steps"] = parsedBrowserSteps
				}
				if cmd.Flags().Changed("check-unique-lines") {
					body["check_unique_lines"] = bodyCheckUniqueLines
				}
				if bodyConditions != "" {
					var parsedConditions any
					if err := json.Unmarshal([]byte(bodyConditions), &parsedConditions); err != nil {
						return fmt.Errorf("parsing --conditions JSON: %w", err)
					}
					body["conditions"] = parsedConditions
				}
				if bodyConditionsMatchLogic != "" {
					body["conditions_match_logic"] = bodyConditionsMatchLogic
				}
				if bodyDateCreated != 0 {
					body["date_created"] = bodyDateCreated
				}
				if bodyExtractLinesContaining != "" {
					parsedExtractLinesContaining, parseErr := cliutil.ParseStringList(bodyExtractLinesContaining)
					if parseErr != nil {
						return fmt.Errorf("parsing --extract-lines-containing list: %w", parseErr)
					}
					body["extract_lines_containing"] = parsedExtractLinesContaining
				}
				if bodyExtractText != "" {
					parsedExtractText, parseErr := cliutil.ParseStringList(bodyExtractText)
					if parseErr != nil {
						return fmt.Errorf("parsing --extract-text list: %w", parseErr)
					}
					body["extract_text"] = parsedExtractText
				}
				if bodyFetchBackend != "" {
					body["fetch_backend"] = bodyFetchBackend
				}
				if cmd.Flags().Changed("filter-failure-notification-send") {
					body["filter_failure_notification_send"] = bodyFilterFailureNotificationSend
				}
				if cmd.Flags().Changed("filter-text-added") {
					body["filter_text_added"] = bodyFilterTextAdded
				}
				if cmd.Flags().Changed("filter-text-removed") {
					body["filter_text_removed"] = bodyFilterTextRemoved
				}
				if cmd.Flags().Changed("filter-text-replaced") {
					body["filter_text_replaced"] = bodyFilterTextReplaced
				}
				if cmd.Flags().Changed("follow-price-changes") {
					body["follow_price_changes"] = bodyFollowPriceChanges
				}
				if cmd.Flags().Changed("has-ldjson-price-data") {
					body["has_ldjson_price_data"] = bodyHasLdjsonPriceData
				}
				if bodyHeaders != "" {
					var parsedHeaders any
					if err := json.Unmarshal([]byte(bodyHeaders), &parsedHeaders); err != nil {
						return fmt.Errorf("parsing --headers JSON: %w", err)
					}
					body["headers"] = parsedHeaders
				}
				if bodyHistorySnapshotMaxLength != 0 {
					body["history_snapshot_max_length"] = bodyHistorySnapshotMaxLength
				}
				if cmd.Flags().Changed("ignore-status-codes") {
					body["ignore_status_codes"] = bodyIgnoreStatusCodes
				}
				if bodyIgnoreText != "" {
					parsedIgnoreText, parseErr := cliutil.ParseStringList(bodyIgnoreText)
					if parseErr != nil {
						return fmt.Errorf("parsing --ignore-text list: %w", parseErr)
					}
					body["ignore_text"] = parsedIgnoreText
				}
				if cmd.Flags().Changed("in-stock-only") {
					body["in_stock_only"] = bodyInStockOnly
				}
				if bodyIncludeFilters != "" {
					parsedIncludeFilters, parseErr := cliutil.ParseStringList(bodyIncludeFilters)
					if parseErr != nil {
						return fmt.Errorf("parsing --include-filters list: %w", parseErr)
					}
					body["include_filters"] = parsedIncludeFilters
				}
				if bodyLlmChangeSummary != "" {
					body["llm_change_summary"] = bodyLlmChangeSummary
				}
				if bodyLlmEvaluationCache != "" {
					var parsedLlmEvaluationCache any
					if err := json.Unmarshal([]byte(bodyLlmEvaluationCache), &parsedLlmEvaluationCache); err != nil {
						return fmt.Errorf("parsing --llm-evaluation-cache JSON: %w", err)
					}
					body["llm_evaluation_cache"] = parsedLlmEvaluationCache
				}
				if bodyLlmIntent != "" {
					body["llm_intent"] = bodyLlmIntent
				}
				if bodyLlmLastTokensUsed != 0 {
					body["llm_last_tokens_used"] = bodyLlmLastTokensUsed
				}
				if bodyLlmPrefilter != "" {
					body["llm_prefilter"] = bodyLlmPrefilter
				}
				if bodyLlmTokensPeriodKey != "" {
					body["llm_tokens_period_key"] = bodyLlmTokensPeriodKey
				}
				if bodyLlmTokensThisPeriod != 0 {
					body["llm_tokens_this_period"] = bodyLlmTokensThisPeriod
				}
				if bodyLlmTokensUsedCumulative != 0 {
					body["llm_tokens_used_cumulative"] = bodyLlmTokensUsedCumulative
				}
				if bodyMethod != "" {
					body["method"] = bodyMethod
				}
				if bodyNotificationBody != "" {
					body["notification_body"] = bodyNotificationBody
				}
				if bodyNotificationFormat != "" {
					body["notification_format"] = bodyNotificationFormat
				}
				if cmd.Flags().Changed("notification-muted") {
					body["notification_muted"] = bodyNotificationMuted
				}
				if cmd.Flags().Changed("notification-screenshot") {
					body["notification_screenshot"] = bodyNotificationScreenshot
				}
				if bodyNotificationTitle != "" {
					body["notification_title"] = bodyNotificationTitle
				}
				if bodyNotificationUrls != "" {
					parsedNotificationUrls, parseErr := cliutil.ParseStringList(bodyNotificationUrls)
					if parseErr != nil {
						return fmt.Errorf("parsing --notification-urls list: %w", parseErr)
					}
					body["notification_urls"] = parsedNotificationUrls
				}
				if cmd.Flags().Changed("paused") {
					body["paused"] = bodyPaused
				}
				if bodyPriceChangeThresholdPercent != 0.0 {
					body["price_change_threshold_percent"] = bodyPriceChangeThresholdPercent
				}
				if bodyProcessor != "" {
					body["processor"] = bodyProcessor
				}
				if bodyProxy != "" {
					body["proxy"] = bodyProxy
				}
				if cmd.Flags().Changed("remove-duplicate-lines") {
					body["remove_duplicate_lines"] = bodyRemoveDuplicateLines
				}
				if cmd.Flags().Changed("sort-text-alphabetically") {
					body["sort_text_alphabetically"] = bodySortTextAlphabetically
				}
				if cmd.Flags().Changed("strip-ignored-lines") {
					body["strip_ignored_lines"] = bodyStripIgnoredLines
				}
				if bodySubtractiveSelectors != "" {
					parsedSubtractiveSelectors, parseErr := cliutil.ParseStringList(bodySubtractiveSelectors)
					if parseErr != nil {
						return fmt.Errorf("parsing --subtractive-selectors list: %w", parseErr)
					}
					body["subtractive_selectors"] = parsedSubtractiveSelectors
				}
				if bodyTag != "" {
					body["tag"] = bodyTag
				}
				if bodyTags != "" {
					parsedTags, parseErr := cliutil.ParseStringList(bodyTags)
					if parseErr != nil {
						return fmt.Errorf("parsing --tags list: %w", parseErr)
					}
					body["tags"] = parsedTags
				}
				if bodyTextShouldNotBePresent != "" {
					parsedTextShouldNotBePresent, parseErr := cliutil.ParseStringList(bodyTextShouldNotBePresent)
					if parseErr != nil {
						return fmt.Errorf("parsing --text-should-not-be-present list: %w", parseErr)
					}
					body["text_should_not_be_present"] = parsedTextShouldNotBePresent
				}
				{
					nestedTimeBetweenCheck := map[string]any{}
					if bodyTimeBetweenCheckDays != 0 {
						nestedTimeBetweenCheck["days"] = bodyTimeBetweenCheckDays
					}
					if bodyTimeBetweenCheckHours != 0 {
						nestedTimeBetweenCheck["hours"] = bodyTimeBetweenCheckHours
					}
					if bodyTimeBetweenCheckMinutes != 0 {
						nestedTimeBetweenCheck["minutes"] = bodyTimeBetweenCheckMinutes
					}
					if bodyTimeBetweenCheckSeconds != 0 {
						nestedTimeBetweenCheck["seconds"] = bodyTimeBetweenCheckSeconds
					}
					if bodyTimeBetweenCheckWeeks != 0 {
						nestedTimeBetweenCheck["weeks"] = bodyTimeBetweenCheckWeeks
					}
					if len(nestedTimeBetweenCheck) > 0 {
						body["time_between_check"] = nestedTimeBetweenCheck
					}
				}
				if cmd.Flags().Changed("time-between-check-use-default") {
					body["time_between_check_use_default"] = bodyTimeBetweenCheckUseDefault
				}
				{
					nestedTimeScheduleLimit := map[string]any{}
					if cmd.Flags().Changed("time-schedule-limit-enabled") {
						nestedTimeScheduleLimit["enabled"] = bodyTimeScheduleLimitEnabled
					}
					{
						nestedTimeScheduleLimitFriday := map[string]any{}
						if cmd.Flags().Changed("time-schedule-limit-friday-enabled") {
							nestedTimeScheduleLimitFriday["enabled"] = bodyTimeScheduleLimitFridayEnabled
						}
						if bodyTimeScheduleLimitFridayStartTime != "" {
							nestedTimeScheduleLimitFriday["start_time"] = bodyTimeScheduleLimitFridayStartTime
						}
						if len(nestedTimeScheduleLimitFriday) > 0 {
							nestedTimeScheduleLimit["friday"] = nestedTimeScheduleLimitFriday
						}
					}
					{
						nestedTimeScheduleLimitMonday := map[string]any{}
						if cmd.Flags().Changed("time-schedule-limit-monday-enabled") {
							nestedTimeScheduleLimitMonday["enabled"] = bodyTimeScheduleLimitMondayEnabled
						}
						if bodyTimeScheduleLimitMondayStartTime != "" {
							nestedTimeScheduleLimitMonday["start_time"] = bodyTimeScheduleLimitMondayStartTime
						}
						if len(nestedTimeScheduleLimitMonday) > 0 {
							nestedTimeScheduleLimit["monday"] = nestedTimeScheduleLimitMonday
						}
					}
					{
						nestedTimeScheduleLimitSaturday := map[string]any{}
						if cmd.Flags().Changed("time-schedule-limit-saturday-enabled") {
							nestedTimeScheduleLimitSaturday["enabled"] = bodyTimeScheduleLimitSaturdayEnabled
						}
						if bodyTimeScheduleLimitSaturdayStartTime != "" {
							nestedTimeScheduleLimitSaturday["start_time"] = bodyTimeScheduleLimitSaturdayStartTime
						}
						if len(nestedTimeScheduleLimitSaturday) > 0 {
							nestedTimeScheduleLimit["saturday"] = nestedTimeScheduleLimitSaturday
						}
					}
					{
						nestedTimeScheduleLimitSunday := map[string]any{}
						if cmd.Flags().Changed("time-schedule-limit-sunday-enabled") {
							nestedTimeScheduleLimitSunday["enabled"] = bodyTimeScheduleLimitSundayEnabled
						}
						if bodyTimeScheduleLimitSundayStartTime != "" {
							nestedTimeScheduleLimitSunday["start_time"] = bodyTimeScheduleLimitSundayStartTime
						}
						if len(nestedTimeScheduleLimitSunday) > 0 {
							nestedTimeScheduleLimit["sunday"] = nestedTimeScheduleLimitSunday
						}
					}
					{
						nestedTimeScheduleLimitThursday := map[string]any{}
						if cmd.Flags().Changed("time-schedule-limit-thursday-enabled") {
							nestedTimeScheduleLimitThursday["enabled"] = bodyTimeScheduleLimitThursdayEnabled
						}
						if bodyTimeScheduleLimitThursdayStartTime != "" {
							nestedTimeScheduleLimitThursday["start_time"] = bodyTimeScheduleLimitThursdayStartTime
						}
						if len(nestedTimeScheduleLimitThursday) > 0 {
							nestedTimeScheduleLimit["thursday"] = nestedTimeScheduleLimitThursday
						}
					}
					{
						nestedTimeScheduleLimitTuesday := map[string]any{}
						if cmd.Flags().Changed("time-schedule-limit-tuesday-enabled") {
							nestedTimeScheduleLimitTuesday["enabled"] = bodyTimeScheduleLimitTuesdayEnabled
						}
						if bodyTimeScheduleLimitTuesdayStartTime != "" {
							nestedTimeScheduleLimitTuesday["start_time"] = bodyTimeScheduleLimitTuesdayStartTime
						}
						if len(nestedTimeScheduleLimitTuesday) > 0 {
							nestedTimeScheduleLimit["tuesday"] = nestedTimeScheduleLimitTuesday
						}
					}
					{
						nestedTimeScheduleLimitWednesday := map[string]any{}
						if cmd.Flags().Changed("time-schedule-limit-wednesday-enabled") {
							nestedTimeScheduleLimitWednesday["enabled"] = bodyTimeScheduleLimitWednesdayEnabled
						}
						if bodyTimeScheduleLimitWednesdayStartTime != "" {
							nestedTimeScheduleLimitWednesday["start_time"] = bodyTimeScheduleLimitWednesdayStartTime
						}
						if len(nestedTimeScheduleLimitWednesday) > 0 {
							nestedTimeScheduleLimit["wednesday"] = nestedTimeScheduleLimitWednesday
						}
					}
					if len(nestedTimeScheduleLimit) > 0 {
						body["time_schedule_limit"] = nestedTimeScheduleLimit
					}
				}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
				if cmd.Flags().Changed("track-ldjson-price-data") {
					body["track_ldjson_price_data"] = bodyTrackLdjsonPriceData
				}
				if bodyTriggerText != "" {
					parsedTriggerText, parseErr := cliutil.ParseStringList(bodyTriggerText)
					if parseErr != nil {
						return fmt.Errorf("parsing --trigger-text list: %w", parseErr)
					}
					body["trigger_text"] = parsedTriggerText
				}
				if cmd.Flags().Changed("trim-text-whitespace") {
					body["trim_text_whitespace"] = bodyTrimTextWhitespace
				}
				if bodyUrl != "" {
					body["url"] = bodyUrl
				}
				if cmd.Flags().Changed("use-page-title-in-list") {
					body["use_page_title_in_list"] = bodyUsePageTitleInList
				}
				if bodyUuid != "" {
					body["uuid"] = bodyUuid
				}
				if bodyWebdriverDelay != 0 {
					body["webdriver_delay"] = bodyWebdriverDelay
				}
				if bodyWebdriverJsExecuteCode != "" {
					body["webdriver_js_execute_code"] = bodyWebdriverJsExecuteCode
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "watch", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "watch", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "watch", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "watch", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "watch", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "watch",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "watch", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "watch", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyBody, "body", "", "HTTP request body")
	cmd.Flags().StringVar(&bodyBrowserSteps, "browser-steps", "", "Browser automation steps. Maximum 100 steps allowed.")
	cmd.Flags().BoolVar(&bodyCheckUniqueLines, "check-unique-lines", false, "Compare against all history for unique lines")
	cmd.Flags().StringVar(&bodyConditions, "conditions", "", "Array of condition rules for change detection logic (empty array when not set)")
	cmd.Flags().StringVar(&bodyConditionsMatchLogic, "conditions-match-logic", "ALL", "Logic operator - ALL (match all conditions) or ANY (match any condition)")
	cmd.Flags().IntVar(&bodyDateCreated, "date-created", 0, "Unix timestamp of creation")
	cmd.Flags().StringVar(&bodyExtractLinesContaining, "extract-lines-containing", "", "Keep only lines containing these substrings (plain text, case-insensitive) — simpler alternative to regex")
	cmd.Flags().StringVar(&bodyExtractText, "extract-text", "", "Regex patterns to extract specific text after filtering")
	cmd.Flags().StringVar(&bodyFetchBackend, "fetch-backend", "system", "Backend to use for fetching content.")
	cmd.Flags().BoolVar(&bodyFilterFailureNotificationSend, "filter-failure-notification-send", true, "Send notification when filters fail to match content")
	cmd.Flags().BoolVar(&bodyFilterTextAdded, "filter-text-added", true, "Include added text in change detection")
	cmd.Flags().BoolVar(&bodyFilterTextRemoved, "filter-text-removed", true, "Include removed text in change detection")
	cmd.Flags().BoolVar(&bodyFilterTextReplaced, "filter-text-replaced", true, "Include replaced text in change detection")
	cmd.Flags().BoolVar(&bodyFollowPriceChanges, "follow-price-changes", true, "Monitor and track price changes (restock_diff processor)")
	cmd.Flags().BoolVar(&bodyHasLdjsonPriceData, "has-ldjson-price-data", false, "Whether page has LD-JSON price data (auto-detected)")
	cmd.Flags().StringVar(&bodyHeaders, "headers", "", "HTTP headers to include in requests")
	cmd.Flags().IntVar(&bodyHistorySnapshotMaxLength, "history-snapshot-max-length", 0, "Maximum number of history snapshots to keep (null = use system default)")
	cmd.Flags().BoolVar(&bodyIgnoreStatusCodes, "ignore-status-codes", false, "Ignore HTTP status code errors (boolean or null)")
	cmd.Flags().StringVar(&bodyIgnoreText, "ignore-text", "", "Text patterns to ignore in change detection")
	cmd.Flags().BoolVar(&bodyInStockOnly, "in-stock-only", true, "Only trigger on in-stock transitions (restock_diff processor)")
	cmd.Flags().StringVar(&bodyIncludeFilters, "include-filters", "", "CSS/XPath selectors to extract specific content from the page")
	cmd.Flags().StringVar(&bodyLlmChangeSummary, "llm-change-summary", "", "Instructions for the AI to summarise changes in notifications.")
	cmd.Flags().StringVar(&bodyLlmEvaluationCache, "llm-evaluation-cache", "", "Internal cache of AI evaluation results keyed by (intent, diff) hash (auto-managed).")
	cmd.Flags().StringVar(&bodyLlmIntent, "llm-intent", "", "Plain-English intent for AI-based change filtering.")
	cmd.Flags().IntVar(&bodyLlmLastTokensUsed, "llm-last-tokens-used", 0, "Number of tokens consumed by the AI on the most recent check.")
	cmd.Flags().StringVar(&bodyLlmPrefilter, "llm-prefilter", "", "CSS selector derived by the AI to narrow content scope before evaluation (auto-managed, do not set manually).")
	cmd.Flags().StringVar(&bodyLlmTokensPeriodKey, "llm-tokens-period-key", "", "Identifier of the current rollover period (e.g. '2026-05').")
	cmd.Flags().IntVar(&bodyLlmTokensThisPeriod, "llm-tokens-this-period", 0, "Tokens consumed by the AI on this watch within the current rollover period (currently month).")
	cmd.Flags().IntVar(&bodyLlmTokensUsedCumulative, "llm-tokens-used-cumulative", 0, "Total tokens consumed by the AI across all checks for this watch.")
	cmd.Flags().StringVar(&bodyMethod, "method", "", "HTTP method to use")
	cmd.Flags().StringVar(&bodyNotificationBody, "notification-body", "", "Custom notification body")
	cmd.Flags().StringVar(&bodyNotificationFormat, "notification-format", "", "Format for notifications")
	cmd.Flags().BoolVar(&bodyNotificationMuted, "notification-muted", false, "Whether notifications are muted")
	cmd.Flags().BoolVar(&bodyNotificationScreenshot, "notification-screenshot", false, "Include screenshot in notifications (if supported by notification URL)")
	cmd.Flags().StringVar(&bodyNotificationTitle, "notification-title", "", "Custom notification title")
	cmd.Flags().StringVar(&bodyNotificationUrls, "notification-urls", "", "Notification URLs for this web page change monitor (watch). Maximum 100 URLs.")
	cmd.Flags().BoolVar(&bodyPaused, "paused", false, "Whether the web page change monitor (watch) is paused")
	cmd.Flags().Float64Var(&bodyPriceChangeThresholdPercent, "price-change-threshold-percent", 0.0, "Minimum price change percentage to trigger notification")
	cmd.Flags().StringVar(&bodyProcessor, "processor", "text_json_diff", "Optional processor mode to use for change detection. Defaults to `text_json_diff` if not specified.")
	cmd.Flags().StringVar(&bodyProxy, "proxy", "", "Proxy configuration")
	cmd.Flags().BoolVar(&bodyRemoveDuplicateLines, "remove-duplicate-lines", false, "Remove duplicate lines from content")
	cmd.Flags().BoolVar(&bodySortTextAlphabetically, "sort-text-alphabetically", false, "Sort lines alphabetically before comparison")
	cmd.Flags().BoolVar(&bodyStripIgnoredLines, "strip-ignored-lines", false, "Remove lines matching ignore patterns")
	cmd.Flags().StringVar(&bodySubtractiveSelectors, "subtractive-selectors", "", "CSS/XPath selectors to remove content from the page")
	cmd.Flags().StringVar(&bodyTag, "tag", "", "Tag UUID to associate with this web page change monitor (watch)")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "Array of tag UUIDs")
	cmd.Flags().StringVar(&bodyTextShouldNotBePresent, "text-should-not-be-present", "", "Text that should NOT be present (triggers alert if found)")
	cmd.Flags().IntVar(&bodyTimeBetweenCheckDays, "time-between-check-days", 0, "Days")
	cmd.Flags().IntVar(&bodyTimeBetweenCheckHours, "time-between-check-hours", 0, "Hours")
	cmd.Flags().IntVar(&bodyTimeBetweenCheckMinutes, "time-between-check-minutes", 0, "Minutes")
	cmd.Flags().IntVar(&bodyTimeBetweenCheckSeconds, "time-between-check-seconds", 0, "Seconds")
	cmd.Flags().IntVar(&bodyTimeBetweenCheckWeeks, "time-between-check-weeks", 0, "Weeks")
	cmd.Flags().BoolVar(&bodyTimeBetweenCheckUseDefault, "time-between-check-use-default", true, "Whether to use global settings for time between checks - defaults to true if not set")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitEnabled, "time-schedule-limit-enabled", false, "Enabled")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitFridayEnabled, "time-schedule-limit-friday-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyTimeScheduleLimitFridayStartTime, "time-schedule-limit-friday-start-time", "", "Start time in HH:MM format")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitMondayEnabled, "time-schedule-limit-monday-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyTimeScheduleLimitMondayStartTime, "time-schedule-limit-monday-start-time", "", "Start time in HH:MM format")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitSaturdayEnabled, "time-schedule-limit-saturday-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyTimeScheduleLimitSaturdayStartTime, "time-schedule-limit-saturday-start-time", "", "Start time in HH:MM format")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitSundayEnabled, "time-schedule-limit-sunday-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyTimeScheduleLimitSundayStartTime, "time-schedule-limit-sunday-start-time", "", "Start time in HH:MM format")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitThursdayEnabled, "time-schedule-limit-thursday-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyTimeScheduleLimitThursdayStartTime, "time-schedule-limit-thursday-start-time", "", "Start time in HH:MM format")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitTuesdayEnabled, "time-schedule-limit-tuesday-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyTimeScheduleLimitTuesdayStartTime, "time-schedule-limit-tuesday-start-time", "", "Start time in HH:MM format")
	cmd.Flags().BoolVar(&bodyTimeScheduleLimitWednesdayEnabled, "time-schedule-limit-wednesday-enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyTimeScheduleLimitWednesdayStartTime, "time-schedule-limit-wednesday-start-time", "", "Start time in HH:MM format")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Custom title for the web page change monitor (watch), not to be confused with page_title")
	cmd.Flags().BoolVar(&bodyTrackLdjsonPriceData, "track-ldjson-price-data", false, "Whether to track JSON-LD price data")
	cmd.Flags().StringVar(&bodyTriggerText, "trigger-text", "", "Text/regex patterns that must be present to trigger a change")
	cmd.Flags().BoolVar(&bodyTrimTextWhitespace, "trim-text-whitespace", false, "Strip leading/trailing whitespace from text")
	cmd.Flags().StringVar(&bodyUrl, "url", "", "URL to monitor for changes")
	cmd.Flags().BoolVar(&bodyUsePageTitleInList, "use-page-title-in-list", false, "Display page title in watch list (null = use system default)")
	cmd.Flags().StringVar(&bodyUuid, "uuid", "", "Unique identifier")
	cmd.Flags().IntVar(&bodyWebdriverDelay, "webdriver-delay", 0, "Delay in seconds for webdriver")
	cmd.Flags().StringVar(&bodyWebdriverJsExecuteCode, "webdriver-js-execute-code", "", "JavaScript code to execute")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin (use this for deeply nested fields not exposed as flags)")

	return cmd
}
