// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newWatchHistoryGetWatchSnapshotCmd(flags *rootFlags) *cobra.Command {
	var flagHtml string

	cmd := &cobra.Command{
		Use:         "get-watch-snapshot <uuid> <timestamp>",
		Short:       "Get single snapshot from web page change monitor (watch). Use 'latest' for the most recent snapshot.",
		Example:     "  changedetection-pp-cli watch history get-watch-snapshot 550e8400-e29b-41d4-a716-446655440000 2026-01-15T09:00:00Z",
		Annotations: map[string]string{"pp:endpoint": "history.get-watch-snapshot", "pp:method": "GET", "pp:path": "/watch/{uuid}/history/{timestamp}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("html") {
				allowedHtml := []string{"1"}
				validHtml := false
				for _, v := range allowedHtml {
					if flagHtml == v {
						validHtml = true
						break
					}
				}
				if !validHtml {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagHtml, "html", allowedHtml)
				}
			}
			path := "/watch/{uuid}/history/{timestamp}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("uuid is required\nUsage: %s <%s>", cmd.CommandPath(), "uuid"))
			}
			path = replacePathParam(path, "uuid", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("timestamp is required\nUsage: %s <%s>", cmd.CommandPath(), "timestamp"))
			}
			path = replacePathParam(path, "timestamp", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagHtml != "" {
				params["html"] = formatCLIParamValue(flagHtml)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "history", false, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagHtml, "html", "", "Set to 1 to return the last HTML (one of: 1)")

	return cmd
}
