// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWatchCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "watch",
		Short:       "List, get, create, update, and delete watch",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWatchCreateCmd(flags))
	cmd.AddCommand(newWatchDeleteCmd(flags))
	cmd.AddCommand(newWatchGetCmd(flags))
	cmd.AddCommand(newWatchListWatchesCmd(flags))
	cmd.AddCommand(newWatchUpdateCmd(flags))
	cmd.AddCommand(newWatchDifferenceCmd(flags))
	cmd.AddCommand(newWatchFaviconCmd(flags))
	cmd.AddCommand(newWatchHistoryCmd(flags))
	return cmd
}
