// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Ad struct {
	Urn        string          `json:"urn"`
	Subject    string          `json:"subject"`
	Body       string          `json:"body"`
	Type       json.RawMessage `json:"type"`
	Category   json.RawMessage `json:"category"`
	Dates      json.RawMessage `json:"dates"`
	Images     json.RawMessage `json:"images"`
	Features   json.RawMessage `json:"features"`
	Advertiser json.RawMessage `json:"advertiser"`
	Geo        json.RawMessage `json:"geo"`
	Urls       json.RawMessage `json:"urls"`
}

type CheckResult struct {
	Newads bool `json:"newads"`
	Count  int  `json:"count"`
}

type Filter struct {
	Uri         string `json:"uri"`
	Type        string `json:"type"`
	Label       string `json:"label"`
	QueryString string `json:"query_string"`
	Datasource  string `json:"datasource"`
}

type Place struct {
	Key          string  `json:"key"`
	Value        string  `json:"value"`
	FriendlyName string  `json:"friendly_name"`
	ShortName    string  `json:"short_name"`
	Istat        string  `json:"istat"`
	Lat          float64 `json:"lat"`
	Lon          float64 `json:"lon"`
}

type Value struct {
	Key             string `json:"key"`
	Value           string `json:"value"`
	FriendlyName    string `json:"friendly_name"`
	MacrocategoryId string `json:"macrocategory_id"`
}

type ValueList struct {
	Values    json.RawMessage `json:"values"`
	TopValues json.RawMessage `json:"top_values"`
}
