// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Handset struct {
	Id   string `json:"Id"`
	Name string `json:"Name"`
}

type Host struct {
	UID      string `json:"UID"`
	Name     string `json:"name"`
	Ip       string `json:"ip"`
	Mac      string `json:"mac"`
	Active   string `json:"active"`
	Guest    string `json:"guest"`
	Ethernet string `json:"ethernet"`
	Wlan     string `json:"wlan"`
}

type QueryResult struct {
	Result string `json:"result"`
}

type Tam struct {
	Name    string `json:"Name"`
	Active  string `json:"Active"`
	Display string `json:"Display"`
}

type WlanInfo struct {
	Ssid    string `json:"ssid"`
	Enabled string `json:"enabled"`
}
