// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is seeded
// at generation time from the verified NovelFeature list that drives the
// SKILL.md feature section, so the command a `which` query returns is
// guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "hosts diff", Description: "See which devices appeared, disappeared, or changed IP on your network since a point in time.", Group: "Local state that compounds", WhyItMatters: "Reach for this when the question is what changed rather than what exists — it is the only way to spot a device that joined the network overnight."},
	{Command: "wan history", Description: "Show how often the internet connection dropped and when, reconstructed from stored uptime samples.", Group: "Local state that compounds", WhyItMatters: "Use this to prove or disprove a flaky line before calling the ISP; a single status call cannot show a pattern."},
	{Command: "log search", Description: "Full-text search the router system log, including entries the router itself has already rotated away.", Group: "Local state that compounds", WhyItMatters: "Reach for this when investigating an incident that happened earlier than the router's log buffer reaches."},
	{Command: "calls digest", Description: "Roll up recent calls by caller with names resolved from the phonebook.", Group: "Telephony that answers questions", WhyItMatters: "Use this for who has been calling; use the raw call list only when individual timestamps matter."},
	{Command: "actions search", Description: "Search the TR-064 action catalog of your own firmware by action, argument, or service name.", Group: "Discovery over a large action surface", WhyItMatters: "Reach for this before guessing at an action name — it maps a plain-language intent onto the exact call this firmware supports."},
	{Command: "presence", Description: "Report who is home by mapping people to their devices and reading stored last-seen times.", Group: "Local state that compounds", WhyItMatters: "Use this when the question is about people rather than devices."},
	{Command: "mesh", Description: "Render the mesh tree of repeaters and their connected clients, with device names resolved.", Group: "Discovery over a large action surface", WhyItMatters: "Reach for this to find out which access point a device is actually attached to."},
	{Command: "health", Description: "One pass, warn, or fail verdict aggregating WAN state, WLAN state, recent log errors, new devices, and firmware currency.", Group: "Local state that compounds", WhyItMatters: "Use this as the first call when something is wrong and you do not yet know where to look."},
	{Command: "actions diff", Description: "Show which TR-064 actions a firmware update added or removed.", Group: "Discovery over a large action surface", WhyItMatters: "Reach for this after a firmware update to find newly available capabilities."},
	{Command: "calls unknown", Description: "List inbound numbers that are not in your phonebook, ranked by how often they called.", Group: "Telephony that answers questions", WhyItMatters: "Use this to find repeat callers worth saving or blocking."},
	{Command: "portmap audit", Description: "Flag port forwarding rules whose target host is no longer known to the router.", Group: "Local state that compounds", WhyItMatters: "Reach for this during a security review; stale forwards are a classic self-hosting footgun."},
	{Command: "energy", Description: "Show power draw broken down by router subsystem, with samples stored for trend queries.", Group: "Discovery over a large action surface", WhyItMatters: "Use this to see which subsystem dominates the router's power budget."},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+2  per-token match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	// Sub-tokenize the query the same way command paths are split, so a
	// pasted hyphenated capability (repos-list-for-authenticated) matches.
	qTokens := whichSubTokens(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		if scored[i].Score != scored[j].Score {
			return scored[i].Score > scored[j].Score
		}
		// Specificity tie-break: at equal score prefer the command with the
		// fewest capability sub-tokens - the canonical operation over variants
		// carrying extra words the request never used.
		return len(whichSubTokens(strings.ToLower(scored[i].Entry.Command))) <
			len(whichSubTokens(strings.ToLower(scored[j].Entry.Command)))
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	// Sub-token split (spaces, hyphens, underscores, slashes): a capability
	// word buried in a hyphenated leaf (repos-list-for-authenticated) must be
	// matchable by the words a human asks with, or every command in a group
	// ties on the group token alone and index order decides the answer.
	cmdTokens := whichSubTokens(cmd)
	desc := strings.ToLower(e.Description)
	descTokens := strings.Fields(desc)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if whichTokenMatch(qt, ct) {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Per-token description match, CAPPED: natural-language requests often say
	// "top coins by market cap" and the endpoint doc uses the same words - but
	// uncapped description credit lets long token-soup descriptions outrank the
	// precise command path, so the credit saturates at 3.
	descCredit := 0
	for _, qt := range qTokens {
		for _, dt := range descTokens {
			if whichTokenMatch(qt, dt) {
				descCredit++
				break
			}
		}
		if descCredit == 3 {
			break
		}
	}
	score += descCredit
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	// Possessive aliasing: "my/mine/me/current" in a request is API-speak for
	// the authenticated caller; commands scoped to the authenticated user must
	// outrank generic listings for possessive asks.
	possessive := false
	for _, qt := range qTokens {
		switch qt {
		case "my", "mine", "me", "current":
			possessive = true
		}
	}
	if possessive {
		for _, ct := range cmdTokens {
			if ct == "authenticated" || ct == "me" {
				score += 3
				break
			}
		}
	}
	// Read-intent default: penalize write-verb commands when the request never
	// asked for a write, so neutral asks can never rank a destructive command
	// first on a tie.
	if score > 0 {
		queryWrite := false
		for _, qt := range qTokens {
			if whichWriteVerbs[qt] {
				queryWrite = true
				break
			}
		}
		if !queryWrite {
			for _, ct := range cmdTokens {
				if whichWriteVerbs[ct] {
					score -= 2
					break
				}
			}
		}
	}
	// Specificity: a command leaf carrying capability sub-tokens the request never
	// used is a variant, not the canonical answer ("activity-list-repos-
	// starred-by-authenticated" for a repositories ask). Parent resource tokens
	// are excluded so a valid nested command is not erased by its path.
	if score > 0 && len(qTokens) > 1 {
		unmatched := 0
		commandParts := strings.Fields(cmd)
		leafTokens := whichSubTokens(commandParts[len(commandParts)-1])
		for _, ct := range leafTokens {
			hit := false
			for _, qt := range qTokens {
				if whichTokenMatch(qt, ct) {
					hit = true
					break
				}
			}
			if !hit {
				unmatched++
			}
		}
		if unmatched > 3 {
			unmatched = 3
		}
		score -= unmatched
	}
	return score
}

func whichTokenMatch(a, b string) bool {
	a = strings.Trim(strings.ToLower(a), ".,:;!?()[]{}\"'")
	b = strings.Trim(strings.ToLower(b), ".,:;!?()[]{}\"'")
	if a == "" || b == "" {
		return false
	}
	if a == b {
		return true
	}
	if whichSingular(a) == whichSingular(b) {
		return true
	}
	return whichTokenAliases[a] != "" && whichTokenAliases[a] == whichTokenAliases[b]
}

func whichSubTokens(cmd string) []string {
	return strings.FieldsFunc(cmd, func(r rune) bool {
		return r == ' ' || r == '-' || r == '_' || r == '/'
	})
}

// The closed API-verb set for write-shaped commands. A request that never
// asked for a write must not tie-break into a destructive command.
var whichWriteVerbs = map[string]bool{
	"delete": true, "remove": true, "update": true, "create": true, "set": true,
	"add": true, "replace": true, "rename": true, "transfer": true, "merge": true,
	"lock": true, "unlock": true, "star": true, "unstar": true, "follow": true,
	"unfollow": true, "block": true, "unblock": true, "mute": true, "archive": true,
	"unarchive": true, "cancel": true, "send": true, "upload": true, "subscribe": true,
	"unsubscribe": true, "dismiss": true, "approve": true, "decline": true,
	"post": true, "put": true, "write": true, "edit": true, "modify": true,
	"publish": true, "share": true, "comment": true, "grant": true, "revoke": true,
}

var whichTokenAliases = map[string]string{
	"repo": "repository", "repos": "repository", "repository": "repository", "repositories": "repository",
}

func whichSingular(s string) string {
	if len(s) > 3 && strings.HasSuffix(s, "ies") {
		return strings.TrimSuffix(s, "ies") + "y"
	}
	if len(s) > 3 && strings.HasSuffix(s, "es") {
		return strings.TrimSuffix(s, "es")
	}
	if len(s) > 2 && strings.HasSuffix(s, "s") {
		return strings.TrimSuffix(s, "s")
	}
	return s
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  fritzbox-pp-cli which "stale tickets"
  fritzbox-pp-cli which "bottleneck"
  fritzbox-pp-cli which --limit 1 "send message"
  fritzbox-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
