// Copyright 2026 Filippo Merante Caparrotta and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type CreateTag struct {
	Body                          string          `json:"body"`
	BrowserSteps                  json.RawMessage `json:"browser_steps"`
	CheckUniqueLines              bool            `json:"check_unique_lines"`
	Conditions                    json.RawMessage `json:"conditions"`
	ConditionsMatchLogic          string          `json:"conditions_match_logic"`
	DateCreated                   int             `json:"date_created"`
	ExtractLinesContaining        json.RawMessage `json:"extract_lines_containing"`
	ExtractText                   json.RawMessage `json:"extract_text"`
	FetchBackend                  string          `json:"fetch_backend"`
	FilterFailureNotificationSend bool            `json:"filter_failure_notification_send"`
	FilterTextAdded               bool            `json:"filter_text_added"`
	FilterTextRemoved             bool            `json:"filter_text_removed"`
	FilterTextReplaced            bool            `json:"filter_text_replaced"`
	FollowPriceChanges            bool            `json:"follow_price_changes"`
	HasLdjsonPriceData            bool            `json:"has_ldjson_price_data"`
	Headers                       json.RawMessage `json:"headers"`
	HistorySnapshotMaxLength      int             `json:"history_snapshot_max_length"`
	IgnoreStatusCodes             bool            `json:"ignore_status_codes"`
	IgnoreText                    json.RawMessage `json:"ignore_text"`
	InStockOnly                   bool            `json:"in_stock_only"`
	IncludeFilters                json.RawMessage `json:"include_filters"`
	LlmChangeSummary              string          `json:"llm_change_summary"`
	LlmEvaluationCache            json.RawMessage `json:"llm_evaluation_cache"`
	LlmIntent                     string          `json:"llm_intent"`
	LlmLastTokensUsed             int             `json:"llm_last_tokens_used"`
	LlmPrefilter                  string          `json:"llm_prefilter"`
	LlmTokensPeriodKey            string          `json:"llm_tokens_period_key"`
	LlmTokensThisPeriod           int             `json:"llm_tokens_this_period"`
	LlmTokensUsedCumulative       int             `json:"llm_tokens_used_cumulative"`
	Method                        string          `json:"method"`
	NotificationBody              string          `json:"notification_body"`
	NotificationFormat            string          `json:"notification_format"`
	NotificationMuted             bool            `json:"notification_muted"`
	NotificationScreenshot        bool            `json:"notification_screenshot"`
	NotificationTitle             string          `json:"notification_title"`
	NotificationUrls              json.RawMessage `json:"notification_urls"`
	OverridesWatch                bool            `json:"overrides_watch"`
	Paused                        bool            `json:"paused"`
	PriceChangeThresholdPercent   float64         `json:"price_change_threshold_percent"`
	Processor                     string          `json:"processor"`
	Proxy                         string          `json:"proxy"`
	RemoveDuplicateLines          bool            `json:"remove_duplicate_lines"`
	SortTextAlphabetically        bool            `json:"sort_text_alphabetically"`
	StripIgnoredLines             bool            `json:"strip_ignored_lines"`
	SubtractiveSelectors          json.RawMessage `json:"subtractive_selectors"`
	Tag                           string          `json:"tag"`
	Tags                          json.RawMessage `json:"tags"`
	TextShouldNotBePresent        json.RawMessage `json:"text_should_not_be_present"`
	TimeBetweenCheck              json.RawMessage `json:"time_between_check"`
	TimeBetweenCheckUseDefault    bool            `json:"time_between_check_use_default"`
	TimeScheduleLimit             json.RawMessage `json:"time_schedule_limit"`
	Title                         string          `json:"title"`
	TrackLdjsonPriceData          bool            `json:"track_ldjson_price_data"`
	TriggerText                   json.RawMessage `json:"trigger_text"`
	TrimTextWhitespace            bool            `json:"trim_text_whitespace"`
	Url                           string          `json:"url"`
	UrlMatchPattern               string          `json:"url_match_pattern"`
	UsePageTitleInList            bool            `json:"use_page_title_in_list"`
	Uuid                          string          `json:"uuid"`
	WebdriverDelay                int             `json:"webdriver_delay"`
	WebdriverJsExecuteCode        string          `json:"webdriver_js_execute_code"`
}

type CreateWatch struct {
	Body                          string          `json:"body"`
	BrowserSteps                  json.RawMessage `json:"browser_steps"`
	CheckUniqueLines              bool            `json:"check_unique_lines"`
	Conditions                    json.RawMessage `json:"conditions"`
	ConditionsMatchLogic          string          `json:"conditions_match_logic"`
	DateCreated                   int             `json:"date_created"`
	ExtractLinesContaining        json.RawMessage `json:"extract_lines_containing"`
	ExtractText                   json.RawMessage `json:"extract_text"`
	FetchBackend                  string          `json:"fetch_backend"`
	FilterFailureNotificationSend bool            `json:"filter_failure_notification_send"`
	FilterTextAdded               bool            `json:"filter_text_added"`
	FilterTextRemoved             bool            `json:"filter_text_removed"`
	FilterTextReplaced            bool            `json:"filter_text_replaced"`
	FollowPriceChanges            bool            `json:"follow_price_changes"`
	HasLdjsonPriceData            bool            `json:"has_ldjson_price_data"`
	Headers                       json.RawMessage `json:"headers"`
	HistorySnapshotMaxLength      int             `json:"history_snapshot_max_length"`
	IgnoreStatusCodes             bool            `json:"ignore_status_codes"`
	IgnoreText                    json.RawMessage `json:"ignore_text"`
	InStockOnly                   bool            `json:"in_stock_only"`
	IncludeFilters                json.RawMessage `json:"include_filters"`
	LlmChangeSummary              string          `json:"llm_change_summary"`
	LlmEvaluationCache            json.RawMessage `json:"llm_evaluation_cache"`
	LlmIntent                     string          `json:"llm_intent"`
	LlmLastTokensUsed             int             `json:"llm_last_tokens_used"`
	LlmPrefilter                  string          `json:"llm_prefilter"`
	LlmTokensPeriodKey            string          `json:"llm_tokens_period_key"`
	LlmTokensThisPeriod           int             `json:"llm_tokens_this_period"`
	LlmTokensUsedCumulative       int             `json:"llm_tokens_used_cumulative"`
	Method                        string          `json:"method"`
	NotificationBody              string          `json:"notification_body"`
	NotificationFormat            string          `json:"notification_format"`
	NotificationMuted             bool            `json:"notification_muted"`
	NotificationScreenshot        bool            `json:"notification_screenshot"`
	NotificationTitle             string          `json:"notification_title"`
	NotificationUrls              json.RawMessage `json:"notification_urls"`
	Paused                        bool            `json:"paused"`
	PriceChangeThresholdPercent   float64         `json:"price_change_threshold_percent"`
	Processor                     string          `json:"processor"`
	Proxy                         string          `json:"proxy"`
	RemoveDuplicateLines          bool            `json:"remove_duplicate_lines"`
	SortTextAlphabetically        bool            `json:"sort_text_alphabetically"`
	StripIgnoredLines             bool            `json:"strip_ignored_lines"`
	SubtractiveSelectors          json.RawMessage `json:"subtractive_selectors"`
	Tag                           string          `json:"tag"`
	Tags                          json.RawMessage `json:"tags"`
	TextShouldNotBePresent        json.RawMessage `json:"text_should_not_be_present"`
	TimeBetweenCheck              json.RawMessage `json:"time_between_check"`
	TimeBetweenCheckUseDefault    bool            `json:"time_between_check_use_default"`
	TimeScheduleLimit             json.RawMessage `json:"time_schedule_limit"`
	Title                         string          `json:"title"`
	TrackLdjsonPriceData          bool            `json:"track_ldjson_price_data"`
	TriggerText                   json.RawMessage `json:"trigger_text"`
	TrimTextWhitespace            bool            `json:"trim_text_whitespace"`
	Url                           string          `json:"url"`
	UsePageTitleInList            bool            `json:"use_page_title_in_list"`
	Uuid                          string          `json:"uuid"`
	WebdriverDelay                int             `json:"webdriver_delay"`
	WebdriverJsExecuteCode        string          `json:"webdriver_js_execute_code"`
}

type DaySchedule struct {
	Duration  json.RawMessage `json:"duration"`
	Enabled   bool            `json:"enabled"`
	StartTime string          `json:"start_time"`
}

type Error struct {
	Message string `json:"message"`
}

type NotificationUrls struct {
	NotificationUrls json.RawMessage `json:"notification_urls"`
}

type SearchResult struct {
	Watches json.RawMessage `json:"watches"`
}

type SystemInfo struct {
	TagCount   int    `json:"tag_count"`
	Uptime     string `json:"uptime"`
	Version    string `json:"version"`
	WatchCount int    `json:"watch_count"`
}

type Tag struct {
	Body                          string          `json:"body"`
	BrowserSteps                  json.RawMessage `json:"browser_steps"`
	CheckUniqueLines              bool            `json:"check_unique_lines"`
	Conditions                    json.RawMessage `json:"conditions"`
	ConditionsMatchLogic          string          `json:"conditions_match_logic"`
	DateCreated                   int             `json:"date_created"`
	ExtractLinesContaining        json.RawMessage `json:"extract_lines_containing"`
	ExtractText                   json.RawMessage `json:"extract_text"`
	FetchBackend                  string          `json:"fetch_backend"`
	FilterFailureNotificationSend bool            `json:"filter_failure_notification_send"`
	FilterTextAdded               bool            `json:"filter_text_added"`
	FilterTextRemoved             bool            `json:"filter_text_removed"`
	FilterTextReplaced            bool            `json:"filter_text_replaced"`
	FollowPriceChanges            bool            `json:"follow_price_changes"`
	HasLdjsonPriceData            bool            `json:"has_ldjson_price_data"`
	Headers                       json.RawMessage `json:"headers"`
	HistorySnapshotMaxLength      int             `json:"history_snapshot_max_length"`
	IgnoreStatusCodes             bool            `json:"ignore_status_codes"`
	IgnoreText                    json.RawMessage `json:"ignore_text"`
	InStockOnly                   bool            `json:"in_stock_only"`
	IncludeFilters                json.RawMessage `json:"include_filters"`
	LlmChangeSummary              string          `json:"llm_change_summary"`
	LlmEvaluationCache            json.RawMessage `json:"llm_evaluation_cache"`
	LlmIntent                     string          `json:"llm_intent"`
	LlmLastTokensUsed             int             `json:"llm_last_tokens_used"`
	LlmPrefilter                  string          `json:"llm_prefilter"`
	LlmTokensPeriodKey            string          `json:"llm_tokens_period_key"`
	LlmTokensThisPeriod           int             `json:"llm_tokens_this_period"`
	LlmTokensUsedCumulative       int             `json:"llm_tokens_used_cumulative"`
	Method                        string          `json:"method"`
	NotificationBody              string          `json:"notification_body"`
	NotificationFormat            string          `json:"notification_format"`
	NotificationMuted             bool            `json:"notification_muted"`
	NotificationScreenshot        bool            `json:"notification_screenshot"`
	NotificationTitle             string          `json:"notification_title"`
	NotificationUrls              json.RawMessage `json:"notification_urls"`
	OverridesWatch                bool            `json:"overrides_watch"`
	Paused                        bool            `json:"paused"`
	PriceChangeThresholdPercent   float64         `json:"price_change_threshold_percent"`
	Processor                     string          `json:"processor"`
	Proxy                         string          `json:"proxy"`
	RemoveDuplicateLines          bool            `json:"remove_duplicate_lines"`
	SortTextAlphabetically        bool            `json:"sort_text_alphabetically"`
	StripIgnoredLines             bool            `json:"strip_ignored_lines"`
	SubtractiveSelectors          json.RawMessage `json:"subtractive_selectors"`
	Tag                           string          `json:"tag"`
	Tags                          json.RawMessage `json:"tags"`
	TextShouldNotBePresent        json.RawMessage `json:"text_should_not_be_present"`
	TimeBetweenCheck              json.RawMessage `json:"time_between_check"`
	TimeBetweenCheckUseDefault    bool            `json:"time_between_check_use_default"`
	TimeScheduleLimit             json.RawMessage `json:"time_schedule_limit"`
	Title                         string          `json:"title"`
	TrackLdjsonPriceData          bool            `json:"track_ldjson_price_data"`
	TriggerText                   json.RawMessage `json:"trigger_text"`
	TrimTextWhitespace            bool            `json:"trim_text_whitespace"`
	Url                           string          `json:"url"`
	UrlMatchPattern               string          `json:"url_match_pattern"`
	UsePageTitleInList            bool            `json:"use_page_title_in_list"`
	Uuid                          string          `json:"uuid"`
	WebdriverDelay                int             `json:"webdriver_delay"`
	WebdriverJsExecuteCode        string          `json:"webdriver_js_execute_code"`
}

type TagCreateResponse struct {
	Uuid string `json:"uuid"`
}

type UpdateWatch struct {
	Body                          string          `json:"body"`
	BrowserSteps                  json.RawMessage `json:"browser_steps"`
	CheckUniqueLines              bool            `json:"check_unique_lines"`
	Conditions                    json.RawMessage `json:"conditions"`
	ConditionsMatchLogic          string          `json:"conditions_match_logic"`
	DateCreated                   int             `json:"date_created"`
	ExtractLinesContaining        json.RawMessage `json:"extract_lines_containing"`
	ExtractText                   json.RawMessage `json:"extract_text"`
	FetchBackend                  string          `json:"fetch_backend"`
	FilterFailureNotificationSend bool            `json:"filter_failure_notification_send"`
	FilterTextAdded               bool            `json:"filter_text_added"`
	FilterTextRemoved             bool            `json:"filter_text_removed"`
	FilterTextReplaced            bool            `json:"filter_text_replaced"`
	FollowPriceChanges            bool            `json:"follow_price_changes"`
	HasLdjsonPriceData            bool            `json:"has_ldjson_price_data"`
	Headers                       json.RawMessage `json:"headers"`
	HistorySnapshotMaxLength      int             `json:"history_snapshot_max_length"`
	IgnoreStatusCodes             bool            `json:"ignore_status_codes"`
	IgnoreText                    json.RawMessage `json:"ignore_text"`
	InStockOnly                   bool            `json:"in_stock_only"`
	IncludeFilters                json.RawMessage `json:"include_filters"`
	LastViewed                    int             `json:"last_viewed"`
	LlmChangeSummary              string          `json:"llm_change_summary"`
	LlmEvaluationCache            json.RawMessage `json:"llm_evaluation_cache"`
	LlmIntent                     string          `json:"llm_intent"`
	LlmLastTokensUsed             int             `json:"llm_last_tokens_used"`
	LlmPrefilter                  string          `json:"llm_prefilter"`
	LlmTokensPeriodKey            string          `json:"llm_tokens_period_key"`
	LlmTokensThisPeriod           int             `json:"llm_tokens_this_period"`
	LlmTokensUsedCumulative       int             `json:"llm_tokens_used_cumulative"`
	Method                        string          `json:"method"`
	NotificationBody              string          `json:"notification_body"`
	NotificationFormat            string          `json:"notification_format"`
	NotificationMuted             bool            `json:"notification_muted"`
	NotificationScreenshot        bool            `json:"notification_screenshot"`
	NotificationTitle             string          `json:"notification_title"`
	NotificationUrls              json.RawMessage `json:"notification_urls"`
	Paused                        bool            `json:"paused"`
	PriceChangeThresholdPercent   float64         `json:"price_change_threshold_percent"`
	Processor                     string          `json:"processor"`
	Proxy                         string          `json:"proxy"`
	RemoveDuplicateLines          bool            `json:"remove_duplicate_lines"`
	SortTextAlphabetically        bool            `json:"sort_text_alphabetically"`
	StripIgnoredLines             bool            `json:"strip_ignored_lines"`
	SubtractiveSelectors          json.RawMessage `json:"subtractive_selectors"`
	Tag                           string          `json:"tag"`
	Tags                          json.RawMessage `json:"tags"`
	TextShouldNotBePresent        json.RawMessage `json:"text_should_not_be_present"`
	TimeBetweenCheck              json.RawMessage `json:"time_between_check"`
	TimeBetweenCheckUseDefault    bool            `json:"time_between_check_use_default"`
	TimeScheduleLimit             json.RawMessage `json:"time_schedule_limit"`
	Title                         string          `json:"title"`
	TrackLdjsonPriceData          bool            `json:"track_ldjson_price_data"`
	TriggerText                   json.RawMessage `json:"trigger_text"`
	TrimTextWhitespace            bool            `json:"trim_text_whitespace"`
	Url                           string          `json:"url"`
	UsePageTitleInList            bool            `json:"use_page_title_in_list"`
	Uuid                          string          `json:"uuid"`
	WebdriverDelay                int             `json:"webdriver_delay"`
	WebdriverJsExecuteCode        string          `json:"webdriver_js_execute_code"`
}

type Watch struct {
	Body                             string          `json:"body"`
	BrowserSteps                     json.RawMessage `json:"browser_steps"`
	BrowserStepsLastErrorStep        int             `json:"browser_steps_last_error_step"`
	CheckCount                       int             `json:"check_count"`
	CheckUniqueLines                 bool            `json:"check_unique_lines"`
	Conditions                       json.RawMessage `json:"conditions"`
	ConditionsMatchLogic             string          `json:"conditions_match_logic"`
	ConsecutiveFilterFailures        int             `json:"consecutive_filter_failures"`
	ContentType                      string          `json:"content-type"`
	DateCreated                      int             `json:"date_created"`
	ExtractLinesContaining           json.RawMessage `json:"extract_lines_containing"`
	ExtractText                      json.RawMessage `json:"extract_text"`
	FetchBackend                     string          `json:"fetch_backend"`
	FetchTime                        float64         `json:"fetch_time"`
	FilterFailureNotificationSend    bool            `json:"filter_failure_notification_send"`
	FilterTextAdded                  bool            `json:"filter_text_added"`
	FilterTextRemoved                bool            `json:"filter_text_removed"`
	FilterTextReplaced               bool            `json:"filter_text_replaced"`
	FollowPriceChanges               bool            `json:"follow_price_changes"`
	HasLdjsonPriceData               bool            `json:"has_ldjson_price_data"`
	Headers                          json.RawMessage `json:"headers"`
	HistoryN                         int             `json:"history_n"`
	HistorySnapshotMaxLength         int             `json:"history_snapshot_max_length"`
	IgnoreStatusCodes                bool            `json:"ignore_status_codes"`
	IgnoreText                       json.RawMessage `json:"ignore_text"`
	InStockOnly                      bool            `json:"in_stock_only"`
	IncludeFilters                   json.RawMessage `json:"include_filters"`
	LastChanged                      int             `json:"last_changed"`
	LastChecked                      int             `json:"last_checked"`
	LastError                        bool            `json:"last_error"`
	LastNotificationError            string          `json:"last_notification_error"`
	LastViewed                       int             `json:"last_viewed"`
	Link                             string          `json:"link"`
	LlmChangeSummary                 string          `json:"llm_change_summary"`
	LlmEvaluationCache               json.RawMessage `json:"llm_evaluation_cache"`
	LlmIntent                        string          `json:"llm_intent"`
	LlmLastTokensUsed                int             `json:"llm_last_tokens_used"`
	LlmPrefilter                     string          `json:"llm_prefilter"`
	LlmTokensPeriodKey               string          `json:"llm_tokens_period_key"`
	LlmTokensThisPeriod              int             `json:"llm_tokens_this_period"`
	LlmTokensUsedCumulative          int             `json:"llm_tokens_used_cumulative"`
	Method                           string          `json:"method"`
	NotificationAlertCount           int             `json:"notification_alert_count"`
	NotificationBody                 string          `json:"notification_body"`
	NotificationFormat               string          `json:"notification_format"`
	NotificationMuted                bool            `json:"notification_muted"`
	NotificationScreenshot           bool            `json:"notification_screenshot"`
	NotificationTitle                string          `json:"notification_title"`
	NotificationUrls                 json.RawMessage `json:"notification_urls"`
	PageTitle                        string          `json:"page_title"`
	Paused                           bool            `json:"paused"`
	PreviousMd5                      bool            `json:"previous_md5"`
	PreviousMd5BeforeFilters         bool            `json:"previous_md5_before_filters"`
	PriceChangeThresholdPercent      float64         `json:"price_change_threshold_percent"`
	Processor                        string          `json:"processor"`
	ProcessorConfigRestockDiff       json.RawMessage `json:"processor_config_restock_diff"`
	ProcessorConfigRestockDiffSource string          `json:"processor_config_restock_diff_source"`
	Proxy                            string          `json:"proxy"`
	RemoteServerReply                string          `json:"remote_server_reply"`
	RemoveDuplicateLines             bool            `json:"remove_duplicate_lines"`
	SortTextAlphabetically           bool            `json:"sort_text_alphabetically"`
	StripIgnoredLines                bool            `json:"strip_ignored_lines"`
	SubtractiveSelectors             json.RawMessage `json:"subtractive_selectors"`
	Tag                              string          `json:"tag"`
	Tags                             json.RawMessage `json:"tags"`
	TextShouldNotBePresent           json.RawMessage `json:"text_should_not_be_present"`
	TimeBetweenCheck                 json.RawMessage `json:"time_between_check"`
	TimeBetweenCheckUseDefault       bool            `json:"time_between_check_use_default"`
	TimeScheduleLimit                json.RawMessage `json:"time_schedule_limit"`
	Title                            string          `json:"title"`
	TrackLdjsonPriceData             bool            `json:"track_ldjson_price_data"`
	TriggerText                      json.RawMessage `json:"trigger_text"`
	TrimTextWhitespace               bool            `json:"trim_text_whitespace"`
	Url                              string          `json:"url"`
	UsePageTitleInList               bool            `json:"use_page_title_in_list"`
	Uuid                             string          `json:"uuid"`
	Viewed                           bool            `json:"viewed"`
	WebdriverDelay                   int             `json:"webdriver_delay"`
	WebdriverJsExecuteCode           string          `json:"webdriver_js_execute_code"`
}

type WatchBase struct {
	Body                          string          `json:"body"`
	BrowserSteps                  json.RawMessage `json:"browser_steps"`
	CheckUniqueLines              bool            `json:"check_unique_lines"`
	Conditions                    json.RawMessage `json:"conditions"`
	ConditionsMatchLogic          string          `json:"conditions_match_logic"`
	DateCreated                   int             `json:"date_created"`
	ExtractLinesContaining        json.RawMessage `json:"extract_lines_containing"`
	ExtractText                   json.RawMessage `json:"extract_text"`
	FetchBackend                  string          `json:"fetch_backend"`
	FilterFailureNotificationSend bool            `json:"filter_failure_notification_send"`
	FilterTextAdded               bool            `json:"filter_text_added"`
	FilterTextRemoved             bool            `json:"filter_text_removed"`
	FilterTextReplaced            bool            `json:"filter_text_replaced"`
	FollowPriceChanges            bool            `json:"follow_price_changes"`
	HasLdjsonPriceData            bool            `json:"has_ldjson_price_data"`
	Headers                       json.RawMessage `json:"headers"`
	HistorySnapshotMaxLength      int             `json:"history_snapshot_max_length"`
	IgnoreStatusCodes             bool            `json:"ignore_status_codes"`
	IgnoreText                    json.RawMessage `json:"ignore_text"`
	InStockOnly                   bool            `json:"in_stock_only"`
	IncludeFilters                json.RawMessage `json:"include_filters"`
	LlmChangeSummary              string          `json:"llm_change_summary"`
	LlmEvaluationCache            json.RawMessage `json:"llm_evaluation_cache"`
	LlmIntent                     string          `json:"llm_intent"`
	LlmLastTokensUsed             int             `json:"llm_last_tokens_used"`
	LlmPrefilter                  string          `json:"llm_prefilter"`
	LlmTokensPeriodKey            string          `json:"llm_tokens_period_key"`
	LlmTokensThisPeriod           int             `json:"llm_tokens_this_period"`
	LlmTokensUsedCumulative       int             `json:"llm_tokens_used_cumulative"`
	Method                        string          `json:"method"`
	NotificationBody              string          `json:"notification_body"`
	NotificationFormat            string          `json:"notification_format"`
	NotificationMuted             bool            `json:"notification_muted"`
	NotificationScreenshot        bool            `json:"notification_screenshot"`
	NotificationTitle             string          `json:"notification_title"`
	NotificationUrls              json.RawMessage `json:"notification_urls"`
	Paused                        bool            `json:"paused"`
	PriceChangeThresholdPercent   float64         `json:"price_change_threshold_percent"`
	Processor                     string          `json:"processor"`
	Proxy                         string          `json:"proxy"`
	RemoveDuplicateLines          bool            `json:"remove_duplicate_lines"`
	SortTextAlphabetically        bool            `json:"sort_text_alphabetically"`
	StripIgnoredLines             bool            `json:"strip_ignored_lines"`
	SubtractiveSelectors          json.RawMessage `json:"subtractive_selectors"`
	Tag                           string          `json:"tag"`
	Tags                          json.RawMessage `json:"tags"`
	TextShouldNotBePresent        json.RawMessage `json:"text_should_not_be_present"`
	TimeBetweenCheck              json.RawMessage `json:"time_between_check"`
	TimeBetweenCheckUseDefault    bool            `json:"time_between_check_use_default"`
	TimeScheduleLimit             json.RawMessage `json:"time_schedule_limit"`
	Title                         string          `json:"title"`
	TrackLdjsonPriceData          bool            `json:"track_ldjson_price_data"`
	TriggerText                   json.RawMessage `json:"trigger_text"`
	TrimTextWhitespace            bool            `json:"trim_text_whitespace"`
	Url                           string          `json:"url"`
	UsePageTitleInList            bool            `json:"use_page_title_in_list"`
	Uuid                          string          `json:"uuid"`
	WebdriverDelay                int             `json:"webdriver_delay"`
	WebdriverJsExecuteCode        string          `json:"webdriver_js_execute_code"`
}

type WatchHistory struct {
}
